Add scripts for importing and stopping MariaDB data
nethesis/ns8-nethvoice pull request #324
Opened 2024-10-21 12:53 UTC by stephdl

This pull request adds two scripts for importing and stopping MariaDB data. The `50import-mariadb` script is used to import MariaDB data using Podman, while the `99_stop_mariadb_import.sh` script is used to stop the temporary MariaDB server. These scripts are useful for managing the import process of MariaDB data.

https://github.com/NethServer/dev/issues/7067

2024-10-22 10:27 UTC, Amygos requested changes
All the tests are failing at the install module step. The journal of the `create-module`:
```
Oct 22 10:09:05 example.leader.example-domain.net agent@nethvoice11[459522]: error: 'Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)'
Oct 22 10:09:05 example.leader.example-domain.net agent@nethvoice11[459522]: Check that mariadbd is running and that the socket: '/run/mysqld/mysqld.sock' exists!
Oct 22 10:09:05 example.leader.example-domain.net agent@nethvoice11[459522]: 2024-10-22 10:09:05+00:00 [ERROR] [Entrypoint]: Unable to shut down server.
Oct 22 10:09:05 example.leader.example-domain.net systemd[459502]: libpod-b6b352be9e03eb2018823e1223dd6a65c2aad57f4b2f69b9c55179a17c34f449.scope: Consumed 5.471s CPU time.
Oct 22 10:09:05 example.leader.example-domain.net agent@nethvoice11[459522]: task/module/nethvoice11/aac5c9fe-0638-4222-973e-92ce05d2e964: action "create-module" status is "aborted" (1) at step 50import-mariadb
Oct 22 10:09:05 example.leader.example-domain.net agent@cluster[455727]: Assertion failed
Oct 22 10:09:05 example.leader.example-domain.net agent@cluster[455727]:   File "/var/lib/nethserver/cluster/actions/add-module/50update", line 223, in <module>
Oct 22 10:09:05 example.leader.example-domain.net agent@cluster[455727]:     agent.assert_exp(create_module_result['exit_code'] == 0) # Ensure create-module is successful
Oct 22 10:09:05 example.leader.example-domain.net agent@cluster[455727]: task/cluster/7895e6d8-e811-415a-a45e-10bc24897893: action "add-module" status is "aborted" (2) at step 50update
```
The action fails because the shutdown of the database in the file [mariadb/docker-entrypoint-initdb.d/99_stop_mariadb_import.sh](https://github.com/nethesis/ns8-nethvoice/pull/324/files#diff-d99eedea525c5258538126af63c401ce1b88ce224d693adf64d744ef67cd2460) conflicts with the shutdown made by the container [entrypoint script](https://github.com/MariaDB/mariadb-docker/blob/cd10ba6c780e49e732ca0eacb76affaac6e87d74/10.8/docker-entrypoint.sh#L148).

2024-10-22 13:02 UTC, Amygos commented
We can use this approach to allow the container to start, perform only the initialization phase, and then gracefully exit.
https://github.com/docker-library/mysql/pull/423#issuecomment-562355462

2024-10-22 13:19 UTC, stephdl commented
it should be good @Amygos

2024-10-22 13:27 UTC, Stell0 approved these changes

2024-10-22 14:15 UTC, Amygos requested changes

2024-10-22 15:16 UTC, stephdl commented on imageroot/actions/create-module/50import-mariadb
> +    --env=ASTMANAGERPORT \
I got a failure and probably I have been added, as you can see we could either add the file or add each variables

2024-10-22 15:20 UTC, Amygos commented on imageroot/actions/create-module/50import-mariadb
> +    --name=mariadb-import \
The file names aren't fixed.

2024-10-22 16:34 UTC, stephdl commented on imageroot/actions/create-module/50import-mariadb
> +    --name=mariadb-import \
done

2024-10-23 07:59 UTC, Amygos commented on imageroot/actions/create-module/50mariadb-init
For clone-module, and restore-module actions, it is not a problem, but I am not sure about import-module.
@stephdl Have you checked it?

2024-10-23 08:41 UTC, stephdl commented on imageroot/actions/create-module/50mariadb-init
restore-module we have an issue

`Oct 23 10:34:08 R2-pve agent@nethvoice2[55974]: [00] 2024-10-23 08:34:08 Original data directory /var/lib/mysql is not empty!`

I think the safer approach is to init the mariadb during the configure module maybe, but we have to test if the volume exists or not

what do you think

2024-10-28 16:00 UTC, stephdl commented
closed https://github.com/nethesis/ns8-nethvoice/pull/326

2024-10-28 16:00 UTC, closed without merging