Update entrypoint.sh
nethesis/ns8-nethvoice pull request #331
Opened 2024-11-06 10:08 UTC by tonyco97

Reference:

https://github.com/NethServer/dev/issues/7087
https://github.com/NethServer/dev/issues/7088

2024-11-07 13:37 UTC, Amygos approved these changes

2024-11-11 07:53 UTC, Stell0 approved these changes

2024-11-11 07:55 UTC, edospadoni approved these changes

2024-11-11 08:03 UTC, gsanchietti requested changes
Please rewrite the commit message.

2024-11-11 09:05 UTC, tonyco97 commented
> Please rewrite the commit message.
Fixed with the correct format

2024-11-11 09:35 UTC, gsanchietti requested changes
Use https://www.conventionalcommits.org/en/v1.0.0/

2024-11-11 10:55 UTC, gsanchietti approved these changes

2024-11-15 10:39 UTC, merged