ui. added nethvoice password env
nethesis/ns8-nethvoice pull request #85
Opened 2023-11-21 10:13 UTC by edospadoni

https://github.com/nethesis/ns8-nethvoice/issues/84

2023-11-21 10:14 UTC, edospadoni commented
UI preview:

![image](https://github.com/nethesis/ns8-nethvoice/assets/6152486/54f789f3-1a81-4195-b57a-2e195be3b445)

2023-11-23 14:44 UTC, Amygos requested changes

2023-11-23 14:44 UTC, Amygos commented on ui/public/metadata.json
> +    "bug_url": "https://github.com/nethesis/dev",
the correct `bug_url` is `https://github.com/NethServer/dev`

2023-11-23 14:58 UTC, Stell0 approved these changes

2023-11-23 15:28 UTC, Amygos approved these changes

2023-11-23 16:27 UTC, merged