Change NethVoice password from `set-nethvoice-admin-password` action
nethesis/ns8-nethvoice pull request #86
Opened 2023-11-22 14:01 UTC by Stell0

2023-11-22 15:38 UTC, Amygos requested changes

2023-11-22 15:38 UTC, Amygos commented on imageroot/actions/set-nethvoice-admin-password/10set_password
> +if 'nethvoice_admin_password' in request:
there is no need for the if, you have defined the field as `required` in the JSON schema.

2023-11-22 15:38 UTC, Amygos commented on imageroot/actions/set-nethvoice-admin-password/10set_password
> +    result = subprocess.run(["systemctl", "--user", "enable", "--now", "mariadb.service"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
this can be done on a previous separeate steps of the action,  to simplify the steps code

2023-11-22 15:38 UTC, Amygos commented on imageroot/actions/create-module/80start_services
Why did you start `mariadb` service here?

2023-11-22 15:43 UTC, Stell0 commented on imageroot/actions/create-module/80start_services
So it's already started when password will be changed. It took some time the first time it starts

2023-11-23 13:59 UTC, Amygos approved these changes

2023-11-23 14:18 UTC, merged